# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFGovqRgsAz1XGj2li_QBJG21OXyOOOj
"""

from sqlite3.dbapi2 import Cursor
import sqlite3

db = sqlite3.connect(':memory:')

cursor = db.cursor()
cursor.execute('''
    CREATE TABLE Ages (
  name VARCHAR(50),
  age INTEGER
)''')


cursor.execute('''DELETE FROM Ages''')

cursor.execute('''INSERT INTO Ages (name, age) VALUES ('Mara', 28)''')
cursor.execute('''INSERT INTO Ages (name, age) VALUES ('Otto', 33)''')
cursor.execute('''INSERT INTO Ages (name, age) VALUES ('Fyn', 31)''')
cursor.execute('''INSERT INTO Ages (name, age) VALUES ('Neshawn', 17)''')
cursor.execute('''INSERT INTO Ages (name, age) VALUES ('Jeeshan', 19)''')


cursor.execute('''SELECT hex(name || age) AS X FROM Ages ORDER BY X''')

user1 = cursor.fetchone()
print("The first row in the resulting record set : "+user1[0])

db.commit()
db.close()